#! /bin/sh
echo "Return parenthesis"
egrep -rn "^ *return \(.*\);$" $1
echo
echo "Missing space before ("
egrep -rn "[^\ \(!]\(" $1
echo
#echo "Missing space after *"
#egrep -rn "[^*/]*.\*[^\ *]" $1
#echo
echo "Space before )"
egrep -rn "^[^\*]*.[^;]\ \)" $1
echo
echo "Space before ;"
egrep -rn "\ ;" $1
echo
echo "Space before ,"
egrep -rn "\ ," $1
echo
#echo "Stuff around operators"
##egrep -rn "[^\+\ ]\+[^=\ ;\+]" $1
#egrep -rn "[\+\ ]\+[^=\ ;\+]" $1
#egrep -rn "[^\+\ ]\+[=\ ;\+]" $1
##egrep -rn "[^\*\ ]\*[^=\ ;\*]" $1
#egrep -rn "[\*\ ]\*[^=\ ;\*]" $1
#egrep -rn "[^\*\ ]\*[=\ ;\*]" $1
##egrep -rn "[^-\ ]-[^=\ ;-]" $1
#egrep -rn "[-\ ]-[^=\ ;-]" $1
#egrep -rn "[^-\ ]-[=\ ;-]" $1
##egrep -rn "[^/\ ]/[^=\ ;/]" $1
#egrep -rn "[/\ ]/[^=\ ;/]" $1
#egrep -rn "[^/\ ]/[=\ ;/]" $1
##egrep -rn "[^%\ ]%[^=\ ;%]" $1
#egrep -rn "[%\ ]%[^=\ ;%]" $1
#egrep -rn "[^%\ ]%[=\ ;%]" $1
