#! /bin/sh

while [ 0 ]; do
  clear
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                       <o>                                      "
  echo "                                                        |                                       "
  echo "                                                        \\\\                                    "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  sleep 1
  clear

  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                       \o/                                      "
  echo "                                                        |                                       "
  echo "                                                        >>                                      "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  echo "                                                                                                "
  sleep 1
done
